version: '3.8'

services:
  cowrie:
    image: cowrie/cowrie:latest
    container_name: cowrie
    hostname: cowrie
    ports:
      - "2222:2222"
      - "2223:2223"
    volumes:
      - ./cowrie-logs:/cowrie/var/log/cowrie
      - cowrie_data:/cowrie/var/lib/cowrie
    environment:
      - COWRIE_HOSTNAME=srv01
      - COWRIE_LOG_LEVEL=INFO
    networks:
      - elastic
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "netstat -tuln | grep 2222 || exit 1"]
      interval: 10h
      timeout: 10s
      retries: 3

  dionaea:
    image: dinotools/dionaea:latest
    container_name: dionaea
    hostname: dionaea
    ports:
      - "21:21"     # FTP
      - "25:25"     # SMTP
      - "69:69/udp" # TFTP
      - "135:135"   # MS-RPC
      - "445:445"   # SMB
      - "1433:1433" # MSSQL
      - "3306:3306" # MySQL
      - "5432:5432" # PostgreSQL
    volumes:
      - ./dionaea-logs:/opt/dionaea/var/log
      - dionaea_data:/opt/dionaea/var/lib/dionaea
    networks:
      - elastic
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    healthcheck:
      test: ["CMD-SHELL", "netstat -tuln | grep 21 || exit 1"]
      interval: 10h
      timeout: 10s
      retries: 3

  redis-honeypot:
    image: redis:7-alpine
    container_name: redis-honeypot
    hostname: redis-honeypot
    ports:
      - "6379:6379"
    volumes:
      - ./redis-logs:/var/log/redis
      - ./redis-honeypot/redis-logger.sh:/usr/local/bin/redis-logger.sh:ro
    networks:
      - elastic
    restart: unless-stopped
    command: >
      sh -c "
        mkdir -p /var/log/redis &&
        touch /var/log/redis/redis.log /var/log/redis/redis-honeypot.json &&
        redis-server --logfile /var/log/redis/redis.log --loglevel verbose --save '' --appendonly no &
        /usr/local/bin/redis-logger.sh &
        wait
      "
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
      interval: 10h
      timeout: 10s
      retries: 3

  snmp-honeypot:
    build:
      context: ./snmp-honeypot
      dockerfile: Dockerfile
    container_name: snmp-honeypot
    hostname: snmp-honeypot
    ports:
      - "161:161/udp"
    volumes:
      - ./snmp-logs:/var/log/snmp
    networks:
      - elastic
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "netstat -uln | grep 161 || exit 1"]
      interval: 10h
      timeout: 10s
      retries: 3

volumes:
  cowrie_data:
    driver: local
  dionaea_data:
    driver: local

networks:
  elastic:
    external: true
    name: elastic